inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  # Exclude anything that isn't really part of our code.
  Exclude:
    - 'Gemfile'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/Vagrantfile'
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1

Rails:
  Enabled: true

# Don't require top-level class documentation
Style/Documentation:
  Enabled: false

# Used throughout app to make deeply nested classes less crazily indented
Style/ClassAndModuleChildren:
  Enabled: false

# Causing too many false positives in methods that memoize multiple things
Naming/MemoizedInstanceVariableName:
  Enabled: false

# Don't apply block length limits where long blocks are unavoidable
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'

# Slightly more lenient line length
# TODO: Specs should adhere to line length too, but too many offending lines to be worth fixing now
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Slightly more lenient module length
Metrics/ModuleLength:
  Max: 120

# Slightly more lenient method length (and ignore in specs - long setup methods)
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

#########

# TODO: These are the most common antipatterns scattered throughout the People Finder specs.
#       It's not worth fixing them any time soon.

RSpec/AnyInstance:
  Enabled: False

RSpec/ContextWording:
  Enabled: False

RSpec/DescribeClass:
  Enabled: False

RSpec/ExampleLength:
  Enabled: False

RSpec/InstanceVariable:
  Enabled: False

RSpec/MessageSpies:
  Enabled: False

RSpec/MultipleExpectations:
  Enabled: False

RSpec/NamedSubject:
  Enabled: False

RSpec/NestedGroups:
  Enabled: False

RSpec/VerifiedDoubles:
  Enabled: False
